# Aula 02
* (continuação dos tipos de variáveis)
* pacote numpy
* pacote pandas
* matblotlib - plotagem de figuras

# Continuação tipos de variáveis

In [52]:
# Exemlo lista

a = [1,2,3,10,20,30]
print (a)

# indexação
print (a[-1])

[1, 2, 3, 10, 20, 30]
30


In [53]:
#determinando o comprimento da lista
b = len(a)
print('o comprimento da lista a é: ' +str(b))

o comprimento da lista a é: 6


## O pacote numpy
https://numpy.org/

Este pacote serve para operações matriciais e estatísticas básicas

In [54]:
# Importanto o numpy
import numpy as np

In [60]:
# criando um número aleatório com numpy

c = np.random.rand(100)

# acessando o último valor do array numpy

print('O último valor de c é:' + str(c[-1]))
print("")

# acessando os 10 primeiros valores

print('Os 10 primeiros valores da lista são:'+str(c[0:10]))

# loop com um numpy array
for ii in range(1,10):
    print(str(ii) +' '+ str(c[ii]))


print("")
# O comprimento do numpy array - shape da matriz
print('O shape da matriz c é:')
print(np.shape(c))

# criando um matriz numpy
d = np.random.rand(100,100)
print(d)

print('Qual é o shape/dimensão da matriz?')
print(np.shape(d))

# Acessando a matriz numpy
# a linha 11 e coluna 11
print('Intexação numpy - matriz 20')
print(d[10,10])

O último valor de c é:0.880025529775699

Os 10 primeiros valores da lista são:[0.69791844 0.70754435 0.86056004 0.65729916 0.96873551 0.7611043
 0.18425292 0.4167349  0.86779909 0.65182913]
1 0.7075443495947179
2 0.8605600368213476
3 0.6572991615483414
4 0.9687355112037687
5 0.7611043026074075
6 0.18425292028450224
7 0.41673490409123337
8 0.8677990944659417
9 0.6518291272568535

O shape da matriz c é:
(100,)
[[0.94907982 0.8213316  0.05457063 ... 0.93482984 0.27744069 0.4794694 ]
 [0.29644996 0.21703683 0.55740855 ... 0.41216267 0.15941554 0.92270041]
 [0.94302329 0.0434942  0.87521612 ... 0.88223466 0.87711381 0.62364248]
 ...
 [0.21713106 0.05572098 0.98292828 ... 0.401042   0.74310965 0.38593372]
 [0.41101969 0.15409593 0.71271486 ... 0.30899446 0.06843309 0.27085787]
 [0.07038069 0.06514862 0.29454373 ... 0.20321241 0.70631931 0.20547811]]
Qual é o shape/dimensão da matriz?
(100, 100)
Intexação numpy - matriz 20
0.7488706468537233


In [57]:
c = np.random.rand(50)
print(c)

for i in range(0,10):
    print(str(i)+' '+str(c[i]))

print(c.shape)

[0.05528529 0.04384103 0.55677478 0.23582703 0.74438536 0.88857975
 0.32643253 0.29041941 0.74670883 0.87935545 0.2812559  0.7659763
 0.28527617 0.54444449 0.40572523 0.41837886 0.21326894 0.29809642
 0.38733485 0.25653051 0.53673362 0.04229847 0.96779886 0.28796758
 0.30067635 0.06364244 0.53980272 0.35421095 0.08053962 0.76788203
 0.42964956 0.21037257 0.48106505 0.57535424 0.60787622 0.95946983
 0.49523291 0.71682666 0.47719113 0.71797701 0.43739112 0.19304886
 0.47096648 0.25631072 0.10506468 0.07280032 0.49694313 0.14573587
 0.50117937 0.92884221]
0 0.055285289400620385
1 0.04384103179181975
2 0.5567747789456162
3 0.23582702704862513
4 0.7443853645891793
5 0.8885797534749398
6 0.32643253329917143
7 0.2904194108801459
8 0.7467088325908082
9 0.8793554485580709
(50,)


In [63]:
# Gerando uma matriz 3D

mat3D = np.random.rand(365,100,100)
print(np.shape(mat3D))

(365, 100, 100)


In [65]:
## acessando todos os valores da primeira dimensão na célua 49, 49

# 10 primeiros valores da série
timeSeries = mat3D[:10,49,49]
print(timeSeries)

# 10 últimos valores da ´serie
timeSeries = mat3D[-10:,49,49]
print(timeSeries)

[0.80973017 0.88298501 0.07004713 0.20253603 0.17223039 0.37694559
 0.13480866 0.82721226 0.82449662 0.44799993]
[0.67034128 0.144521   0.88399822 0.45530554 0.09102995 0.39088051
 0.14712971 0.05935814 0.63557429 0.7009002 ]


In [69]:

timeSeries2 = mat3D[:,50:52,50]
print(np.shape(timeSeries2))
print(timeSeries2.shape)

timeSeriesTransposta = timeSeries2.transpose()
print(timeSeriesTransposta.shape)

(365, 2)
(365, 2)
(2, 365)


In [75]:
# Estatística com numpy

mediaTS = np.mean(timeSeries2)
print(mediaTS)

# média das colunas
mediaTScolums = np.mean(timeSeries2,axis=0)
print(mediaTScolums)

# média nas linhas 
print('essa é a média de cada linha')
mediaTSrpw = np.mean(timeSeries2,axis=1)
print(mediaTSrows.shape)

0.4932097845935318
[0.49699846 0.48942111]
essa é a média de cada linha


NameError: name 'mediaTSrows' is not defined

In [87]:
# média míniimo, máximo, desvio, percentil, mediana, variância

#média
media3D = np.mean(mat3D)
print(media3D)

#mínimo
min3D = np.min(mat3D)
print(min3D)

#percentil
pct3D = np.percentile(mat3D,90)
print(pct3D)

#mediana
median3D = np.median(mat3D)
print(median3D)

#mvariancia
var3D = std3D**2
print(var3D)
var3D = np.var(mat3D)
print(var3D)

0.5000145009351327
2.0788416232875306e-07
0.8998988186381836
0.4999518625078547


NameError: name 'std3D' is not defined

# plotando com matplotlib
"plot
-histogram
-barbox
-pcolor

In [97]:
# imprortando o pacote matplotlib

import matplotlib.pyplot as plt

fig.aux = plt.subplot(3)
print(fig.aux)


# boxplot

fig.ax = plt.subplot()
ax.boxplot(mat3d[:,10:20,0]

SyntaxError: incomplete input (4144091814.py, line 12)

In [96]:
import pandas as pd

path = r'C:\Users\rafael.shibayama\Documents\GitHub\ENS410064\2024\cnuc_2024_02-2.csv'
df = pd.read_csv(path)

ParserError: Error tokenizing data. C error: Expected 4 fields in line 3, saw 5
